# Generated by Django 5.0.7 on 2024-10-04 07:28

import django.db.models.deletion
import nepali_datetime_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "organization",
            "0035_alter_employee_options_alter_employee_basic_salary_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("danger", "Red"),
                            ("primary", "Blue"),
                            ("warning", "Yellow"),
                            ("secondary", "Light blue"),
                            ("success", "Green"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(null=True)),
                ("start", nepali_datetime_field.models.NepaliDateField(null=True)),
                ("end", nepali_datetime_field.models.NepaliDateField(null=True)),
                ("location", models.CharField(max_length=255, null=True)),
                (
                    "categories",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendar_app.category",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="organization.organization",
                    ),
                ),
            ],
        ),
    ]
