# Generated by Django 5.0.7 on 2024-11-06 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0001_initial"),
        ("organization", "0043_alter_address_employee_alter_document_employee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="category",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.organization",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(
                choices=[
                    ("danger", "Red"),
                    ("primary", "Blue"),
                    ("warning", "Yellow"),
                    ("info", "Light blue"),
                    ("success", "Green"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
