# Generated by Django 5.0.7 on 2024-11-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0002_alter_category_options_category_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_holiday",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
