# Generated by Django 5.0.7 on 2024-11-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0003_event_is_holiday"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="categories",
            new_name="category",
        ),
    ]
