# Generated by Django 5.0.7 on 2026-07-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_rename_categories_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_important',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
