# Generated by Django 5.0.6 on 2024-05-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='image',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(default='placeholder/placeholder.png', upload_to='users/'),
        ),
    ]
