# Generated by Django 5.0.7 on 2024-08-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_loginhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginhistory',
            old_name='logged_in_device',
            new_name='browser',
        ),
        migrations.RenameField(
            model_name='loginhistory',
            old_name='last_logged_in',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='os',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
