# Generated by Django 5.0.7 on 2024-10-27 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0004_rename_logged_in_device_loginhistory_browser_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="username",
        ),
    ]
