# Generated by Django 5.0.7 on 2026-07-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_account_date_joined_alter_account_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_hr',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
