# Generated by Django 5.0.6 on 2024-05-27 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_department_department_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organization.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='organization.department'),
        ),
    ]
