# Generated by Django 5.0.6 on 2024-05-28 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_department_organization_alter_employee_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_level',
            field=models.CharField(blank=True, choices=[('internship', 'Internship'), ('junior', 'Junior'), ('senior', 'Senior')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hired_status',
            field=models.CharField(blank=True, choices=[('full_time', 'Full time'), ('part_time', 'Part time')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='temporary_address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeRelatedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='employee/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='organization.employee')),
            ],
        ),
    ]
