# Generated by Django 5.0.6 on 2024-05-28 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_employee_contact_number_employee_contract_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organization.post', verbose_name='designation'),
        ),
    ]
