# Generated by Django 5.0.6 on 2024-05-29 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_employee_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship', models.FileField(blank=True, null=True, upload_to='employee/')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='employee/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='employee/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='employee/')),
                ('contract', models.FileField(blank=True, null=True, upload_to='employee/')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_document', to='organization.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAcademicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='employee/')),
                ('employee_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_files', to='organization.employeedocument')),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeRelatedDocument',
        ),
    ]
