# Generated by Django 5.0.6 on 2024-05-29 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_employeedocument_employeeacademicdocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_document', to='organization.employee'),
        ),
        migrations.CreateModel(
            name='OtherDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='employee/')),
                ('employee_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_files', to='organization.employeedocument')),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeAcademicDocument',
        ),
    ]
