# Generated by Django 5.0.6 on 2024-06-19 05:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_alter_employeedocument_employee_otherdocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='admin_users',
            field=models.ManyToManyField(related_name='organization', to=settings.AUTH_USER_MODEL),
        ),
    ]
