# Generated by Django 5.0.6 on 2024-06-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_organization_admin_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='static_ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
    ]
