# Generated by Django 5.0.6 on 2024-06-24 10:34

import nepali_datetime_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_organization_static_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=nepali_datetime_field.models.NepaliDateField(blank=True, null=True),
        ),
    ]
