# Generated by Django 5.0.6 on 2024-06-28 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_employee_id_prefix_alter_employee_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.employee'),
        ),
    ]
