# Generated by Django 5.0.6 on 2024-06-28 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_alter_department_department_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organization.post', verbose_name='designation'),
        ),
    ]
