# Generated by Django 5.0.6 on 2024-06-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_alter_employee_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='admin_users',
            field=models.ManyToManyField(related_name='organization', to='organization.employee'),
        ),
    ]
