# Generated by Django 5.0.6 on 2024-06-28 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_alter_organization_admin_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.employee'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='admin_users',
            field=models.ManyToManyField(related_name='organization', to=settings.AUTH_USER_MODEL),
        ),
    ]
