# Generated by Django 5.0.6 on 2024-06-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_employee_basic_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
