# Generated by Django 5.0.6 on 2024-07-02 05:08

import nepali_datetime_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_organization_closing_time_organization_opening_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contract_end_date',
            field=nepali_datetime_field.models.NepaliDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=nepali_datetime_field.models.NepaliDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hired_date',
            field=nepali_datetime_field.models.NepaliDateField(blank=True, null=True),
        ),
    ]
