# Generated by Django 5.0.6 on 2024-07-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0022_alter_employee_contract_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_prefix',
            field=models.CharField(blank=True, default='EMP', max_length=255, null=True),
        ),
    ]
