# Generated by Django 5.0.6 on 2024-07-04 10:53

import django.db.models.deletion
import nepali_datetime_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0023_alter_employee_id_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', nepali_datetime_field.models.NepaliDateField(blank=True, null=True)),
                ('task_score', models.FloatField(default=0)),
                ('attendance_score', models.FloatField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
    ]
