# Generated by Django 5.0.6 on 2024-07-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0024_employeeanalysisreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='static_ip',
        ),
    ]
