# Generated by Django 5.0.6 on 2024-07-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_remove_organization_static_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationtype',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
