# Generated by Django 5.0.7 on 2024-07-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0027_organization_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='status',
            new_name='is_active',
        ),
    ]
