# Generated by Django 5.0.7 on 2024-09-06 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0030_organizationfolder_organizationfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationfile',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organizationfolder'),
        ),
        migrations.AlterField(
            model_name='organizationfile',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
    ]
