# Generated by Django 5.0.7 on 2024-09-06 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0031_alter_organizationfile_folder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationfile',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='organization.organizationfolder'),
        ),
        migrations.AlterField(
            model_name='organizationfile',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='organizationfolder',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='organizationfolder',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organizationfolder'),
        ),
    ]
