# Generated by Django 5.0.7 on 2024-09-06 17:40

import organization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0032_alter_organizationfile_folder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationfile',
            name='file',
            field=models.FileField(upload_to=organization.models.file_upload_path),
        ),
    ]
