# Generated by Django 5.0.7 on 2024-09-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0033_alter_organizationfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationfile',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
