# Generated by Django 5.0.7 on 2024-09-10 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0034_alter_organizationfile_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
            },
        ),
        migrations.AlterField(
            model_name="employee",
            name="basic_salary",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="employee",
            name="contact_number",
            field=models.CharField(blank=True, default="", max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("internship", "Internship"),
                    ("junior", "Junior"),
                    ("senior", "Senior"),
                ],
                default="",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("others", "Others")],
                default="",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="highest_qualification",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="hired_status",
            field=models.CharField(
                blank=True,
                choices=[("full_time", "Full time"), ("part_time", "Part time")],
                default="",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="permanent_address",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="organization.post",
                verbose_name="Designation",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="temporary_address",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
    ]
