# Generated by Django 5.0.7 on 2024-10-25 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organization",
            "0035_alter_employee_options_alter_employee_basic_salary_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=255, null=True)),
                ("district", models.CharField(max_length=255, null=True)),
                ("street", models.CharField(max_length=255, null=True)),
                ("type", models.CharField(max_length=255, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.employee",
                    ),
                ),
            ],
        ),
    ]
