# Generated by Django 5.0.7 on 2024-10-27 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0036_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="basic_salary",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="contact_number",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="contract_end_date",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="employee_level",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="highest_qualification",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="hired_date",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="hired_status",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="permanent_address",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="temporary_address",
        ),
        migrations.AddField(
            model_name="employee",
            name="father_name",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Father's name"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="official_email",
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="personal_email",
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="phone_no",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="BankDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                ("account_holder_name", models.CharField(blank=True, max_length=255)),
                ("account_number", models.CharField(blank=True, max_length=255)),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="employee/"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NationalIDDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "national_id_no",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "citizenship_no",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("martial_status", models.CharField(max_length=255, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("college", models.CharField(blank=True, max_length=255, null=True)),
                ("degree", models.CharField(max_length=255, null=True)),
                ("field_of_study", models.CharField(max_length=255, null=True)),
                ("start_date", models.CharField(max_length=255, null=True)),
                ("end_date", models.CharField(max_length=255, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.employee",
                    ),
                ),
            ],
        ),
    ]
