# Generated by Django 5.0.7 on 2024-10-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0037_remove_employee_basic_salary_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NationalIDDetails",
            new_name="NationalIdDetail",
        ),
    ]
