# Generated by Django 5.0.7 on 2024-10-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0038_rename_nationaliddetails_nationaliddetail"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BankDetails",
            new_name="BankDetail",
        ),
    ]
