# Generated by Django 5.0.7 on 2024-10-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0039_rename_bankdetails_bankdetail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankdetail",
            name="account_holder_name",
        ),
    ]
