# Generated by Django 5.0.7 on 2024-10-30 05:57

import django.db.models.deletion
import nepali_datetime_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0040_remove_bankdetail_account_holder_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="date_of_birth",
            field=nepali_datetime_field.models.NepaliDateField(null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="father_name",
            field=models.CharField(
                default="", max_length=255, verbose_name="Father's name"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("others", "Others")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="official_email",
            field=models.EmailField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="personal_email",
            field=models.EmailField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone_no",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="organization.post",
                verbose_name="Designation",
            ),
        ),
    ]
