# Generated by Django 5.0.7 on 2024-10-30 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0041_alter_employee_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualification",
            name="college",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qualification",
                to="organization.employee",
            ),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
