# Generated by Django 5.0.7 on 2024-11-06 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0042_alter_qualification_college_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="organization.employee",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="organization.employee",
            ),
        ),
    ]
