# Generated by Django 5.0.7 on 2024-11-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0043_alter_address_employee_alter_document_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="department_lead",
        ),
    ]
