# Generated by Django 5.0.7 on 2024-12-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0044_remove_department_department_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="types",
            field=models.CharField(
                choices=[
                    ("full_time", "Full time"),
                    ("part_time", "Part time"),
                    ("intern", "Intern"),
                ],
                default="full_time",
                max_length=255,
                null=True,
            ),
        ),
    ]
