# Generated by Django 5.0.7 on 2024-12-10 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0045_employee_types"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="types",
            new_name="employee_type",
        ),
    ]
