# Generated by Django 5.0.7 on 2024-12-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0046_rename_types_employee_employee_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationaddress",
            name="latitude",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="organizationaddress",
            name="longitude",
            field=models.FloatField(default=0),
        ),
    ]
