# Generated by Django 5.0.7 on 2024-12-23 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0047_organizationaddress_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nationaliddetail",
            name="employee",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="national_id",
                to="organization.employee",
            ),
        ),
    ]
