# Generated by Django 5.0.7 on 2026-07-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0048_alter_nationaliddetail_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='alternative_contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
