# Generated by Django 5.0.7 on 2026-07-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0050_employee_deleted_at_employee_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='alternative_contact_number',
            new_name='emergency_phone_number',
        ),
        migrations.AddField(
            model_name='employee',
            name='grandfather_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Grandfather's name"),
        ),
    ]
