# Generated by Django 5.0.7 on 2026-07-27 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0051_rename_alternative_contact_number_employee_emergency_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], default='single', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_latitude', models.FloatField(blank=True, null=True)),
                ('office_longitude', models.FloatField(blank=True, null=True)),
                ('allowed_attendance_radius', models.IntegerField(default=100, help_text='Radius in meters')),
                ('enable_in_office_attendance', models.BooleanField(default=True)),
                ('enable_remote_attendance', models.BooleanField(default=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organization.organization')),
            ],
        ),
    ]
