# Generated by Django 5.0.7 on 2026-08-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0053_employee_profile_change_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetail',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
