# Generated by Django 5.0.7 on 2026-08-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0054_bankdetail_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pan_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PAN Number'),
        ),
    ]
