# Generated by Django 5.0.7 on 2024-11-20 06:09

import django.db.models.deletion
import django_ckeditor_5.fields
import nepali_datetime_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0043_alter_address_employee_alter_document_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                ("created_at", nepali_datetime_field.models.NepaliDateField()),
                ("updated_at", nepali_datetime_field.models.NepaliDateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                ("file", models.FileField(upload_to="")),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="task_management.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project file",
                "verbose_name_plural": "Project files",
            },
        ),
    ]
