# Generated by Django 5.0.7 on 2024-11-20 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0043_alter_address_employee_alter_document_employee"),
        ("task_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="orgnization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.organization",
            ),
        ),
    ]
