# Generated by Django 5.0.7 on 2024-11-20 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0002_project_orgnization"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="orgnization",
            new_name="organization",
        ),
    ]
