# Generated by Django 5.0.7 on 2024-11-20 07:00

import django.db.models.deletion
import django_ckeditor_5.fields
import nepali_datetime_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0043_alter_address_employee_alter_document_employee"),
        ("task_management", "0003_rename_orgnization_project_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to-do", "To Do"),
                            ("in-progress", "In Progress"),
                            ("done", "Done"),
                        ],
                        default="to-do",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", nepali_datetime_field.models.NepaliDateField()),
                ("updated_at", nepali_datetime_field.models.NepaliDateField()),
                ("planned_start_date", nepali_datetime_field.models.NepaliDateField()),
                ("planned_end_date", nepali_datetime_field.models.NepaliDateField()),
                ("actual_start_date", nepali_datetime_field.models.NepaliDateField()),
                ("actual_end_date", nepali_datetime_field.models.NepaliDateField()),
                (
                    "assigned_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_tasks",
                        to="organization.employee",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to="organization.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="task_management.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_tasks",
                        to="organization.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                ("file", models.FileField(upload_to="")),
                (
                    "task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="task_management.task",
                    ),
                ),
            ],
        ),
    ]
