# Generated by Django 5.0.7 on 2024-11-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0004_task_taskfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                default="low",
                max_length=255,
                null=True,
            ),
        ),
    ]
