# Generated by Django 5.0.7 on 2024-11-21 09:22

import nepali_datetime_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0005_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=nepali_datetime_field.models.NepaliDateField(null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=nepali_datetime_field.models.NepaliDateField(null=True),
        ),
    ]
