# Generated by Django 5.0.7 on 2024-11-21 09:26

import nepali_datetime_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0006_alter_task_created_at_alter_task_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="actual_end_date",
            field=nepali_datetime_field.models.NepaliDateField(null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="actual_start_date",
            field=nepali_datetime_field.models.NepaliDateField(null=True),
        ),
    ]
