# Generated by Django 5.0.7 on 2024-11-22 07:53

import nepali_datetime_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0007_alter_task_actual_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=nepali_datetime_field.models.NepaliDateField(
                auto_now=True, null=True
            ),
        ),
    ]
