# Generated by Django 5.0.7 on 2024-11-22 10:37

import nepali_datetime_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0008_alter_task_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="abbreviation",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=nepali_datetime_field.models.NepaliDateField(null=True),
        ),
    ]
