# Generated by Django 5.0.7 on 2026-07-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0010_project_deleted_at_project_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
