# Generated by Django 5.0.7 on 2026-08-03 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0053_employee_profile_change_request'),
        ('task_management', '0011_task_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily'), ('hourly', 'Hourly')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('incomplete', 'Incomplete'), ('complete', 'Complete')], default='ongoing', max_length=12),
        ),
        migrations.AddField(
            model_name='project',
            name='total_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='description_pdf',
            field=models.FileField(blank=True, null=True, upload_to='task_description_pdfs/'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily')], default='daily', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to='project_attachments/'),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(upload_to='task_attachments/'),
        ),
        migrations.CreateModel(
            name='TaskProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='task_progress_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_reports', to='organization.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='task_management.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('senior', 'Senior'), ('junior', 'Junior')], default='junior', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='organization.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='task_management.project')),
            ],
            options={
                'unique_together': {('project', 'employee')},
            },
        ),
    ]
