# Generated by Django 5.0.7 on 2026-08-21 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0054_bankdetail_account_name'),
        ('task_management', '0013_projectassignment_daily_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprogressreport',
            name='deletion_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskprogressreport',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskprogressreport',
            name='deletion_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requested_reports', to='organization.employee'),
        ),
        migrations.AddField(
            model_name='taskprogressreport',
            name='is_deletion_requested',
            field=models.BooleanField(default=False),
        ),
    ]
