# Generated by Django 5.0.6 on 2024-05-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
