# Generated by Django 5.0.6 on 2024-05-28 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_leaverequest_is_reviewed'),
        ('organization', '0005_alter_employee_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='maximum_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LeaveQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('no_of_leaves', models.IntegerField()),
                ('maximum_leave', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_quota', to='organization.employee')),
            ],
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_quota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='leave_management.leavequota'),
        ),
    ]
