# Generated by Django 5.0.6 on 2024-05-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_leavetype_maximum_leave_leavequota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='maximum_leave',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
