# Generated by Django 5.0.6 on 2024-05-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0004_alter_leavetype_maximum_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavequota',
            name='maximum_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leavequota',
            name='no_of_leaves',
            field=models.IntegerField(default=0),
        ),
    ]
