# Generated by Django 5.0.6 on 2024-05-29 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0005_alter_leavequota_maximum_leave_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavequota',
            name='date',
        ),
        migrations.AddField(
            model_name='leavequota',
            name='year',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.CreateModel(
            name='LeaveRequestFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='leave_requests/')),
                ('leave_quota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='leave_management.leaverequest')),
            ],
        ),
    ]
