# Generated by Django 5.0.6 on 2024-05-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0006_remove_leavequota_date_leavequota_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavequota',
            name='year',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
