# Generated by Django 5.0.6 on 2024-05-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0007_alter_leavequota_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavequota',
            name='month',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
