# Generated by Django 5.0.6 on 2024-05-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0008_leavequota_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavequota',
            name='month',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='leavequota',
            name='year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
