# Generated by Django 5.0.6 on 2024-07-02 05:39

import nepali_datetime_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0009_alter_leavequota_month_alter_leavequota_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='from_date',
            field=nepali_datetime_field.models.NepaliDateField(),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='till_date',
            field=nepali_datetime_field.models.NepaliDateField(),
        ),
    ]
