# Generated by Django 5.0.6 on 2024-07-03 08:13

import nepali_datetime_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0010_alter_leaverequest_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='created_at',
            field=nepali_datetime_field.models.NepaliDateField(),
        ),
    ]
