# Generated by Django 5.0.6 on 2024-07-03 08:14

import nepali_datetime_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0011_alter_leaverequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='created_at',
            field=nepali_datetime_field.models.NepaliDateField(blank=True, null=True),
        ),
    ]
