# Generated by Django 5.0.6 on 2024-07-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0012_alter_leaverequest_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='leave_quota',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='LeaveQuota',
        ),
    ]
