# Generated by Django 5.0.7 on 2024-09-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0013_remove_leaverequest_leave_quota_leaverequest_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='color',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning')], default='primary', max_length=255),
            preserve_default=False,
        ),
    ]
