# Generated by Django 5.0.7 on 2024-10-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0014_leavetype_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavetype",
            name="max_leave_per_week",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
