# Generated by Django 5.0.7 on 2024-10-06 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0015_leavetype_max_leave_per_week"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaverequestfiles",
            name="leave_quota",
        ),
        migrations.AddField(
            model_name="leaverequestfiles",
            name="leave_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="leave_management.leaverequest",
            ),
        ),
    ]
