# Generated by Django 5.0.7 on 2024-10-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0016_remove_leaverequestfiles_leave_quota_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavetype",
            name="max_leave_per_week",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
