# Generated by Django 5.0.7 on 2024-11-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0017_alter_leavetype_max_leave_per_week"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaverequest",
            name="is_paid",
        ),
    ]
