# Generated by Django 5.0.7 on 2024-11-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0018_remove_leaverequest_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
