# Generated by Django 5.0.7 on 2024-11-13 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0019_leaverequest_is_paid"),
        ("organization", "0043_alter_address_employee_alter_document_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leavetype",
            name="color",
        ),
        migrations.RemoveField(
            model_name="leavetype",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="leavetype",
            name="max_leave_per_week",
        ),
        migrations.RemoveField(
            model_name="leavetype",
            name="maximum_leave",
        ),
        migrations.RemoveField(
            model_name="leavetype",
            name="slug",
        ),
        migrations.AddField(
            model_name="leavetype",
            name="quota",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="LeaveQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quota", models.IntegerField(default=0)),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leave_management.leavetype",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.organization",
                    ),
                ),
            ],
        ),
    ]
