# Generated by Django 5.0.7 on 2024-11-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "leave_management",
            "0020_remove_leavetype_color_remove_leavetype_is_paid_and_more",
        ),
        ("organization", "0043_alter_address_employee_alter_document_employee"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LeaveQuota",
            new_name="LeaveBalance",
        ),
    ]
