# Generated by Django 5.0.7 on 2024-11-13 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0021_rename_leavequota_leavebalance"),
        ("organization", "0043_alter_address_employee_alter_document_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.organization",
            ),
        ),
    ]
