# Generated by Django 5.0.7 on 2024-11-15 09:55

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0022_leaverequest_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavebalance",
            name="leaves_taken",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="reason_for_leave",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
