# Generated by Django 5.0.7 on 2024-12-04 06:07

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0023_leavebalance_leaves_taken_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="reason_for_leave",
            field=tinymce.models.HTMLField(default=""),
            preserve_default=False,
        ),
    ]
