# Generated by Django 5.0.7 on 2024-12-04 07:48

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0024_alter_leaverequest_reason_for_leave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="reason_for_leave",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
