# Generated by Django 5.0.7 on 2026-07-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0025_alter_leaverequest_reason_for_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='half_day_period',
            field=models.CharField(blank=True, choices=[('First Half', 'First Half'), ('Second Half', 'Second Half')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
    ]
