# Generated by Django 5.0.7 on 2026-07-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0026_leaverequest_half_day_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='leaves_taken',
            field=models.FloatField(default=0, null=True),
        ),
    ]
