# Generated by Django 5.0.7 on 2026-08-21 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0028_leaverequest_deleted_at_leaverequest_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='initial_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='initial_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_approved_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_initial_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='rejection_reason',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_casual_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_sick_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='remarks',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
    ]
