# Generated by Django 5.0.6 on 2024-06-28 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
        ('organization', '0011_employee_id_prefix_alter_employee_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylogs',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='activitylogs',
            name='log_description',
        ),
        migrations.RemoveField(
            model_name='activitylogs',
            name='log_title',
        ),
        migrations.RemoveField(
            model_name='activitylogs',
            name='log_user',
        ),
        migrations.AddField(
            model_name='activitylogs',
            name='action',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='activitylogs',
            name='employee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activitylogs',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='activitylogs',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
