# Generated by Django 5.0.6 on 2024-06-28 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_remove_activitylogs_ip_address_and_more'),
        ('organization', '0011_employee_id_prefix_alter_employee_date_of_birth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityLogs',
            new_name='ActivityLog',
        ),
    ]
