# Generated by Django 5.0.7 on 2024-09-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0003_webpushdevice"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebPushDevice",
        ),
    ]
