# Generated by Django 5.0.7 on 2024-11-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0004_delete_webpushdevice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(max_length=500),
        ),
    ]
