# Generated by Django 5.0.6 on 2024-07-02 05:39

import nepali_datetime_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=nepali_datetime_field.models.NepaliDateField(auto_now_add=True),
        ),
    ]
