# Generated by Django 5.0.6 on 2024-07-03 07:53

import nepali_datetime_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=nepali_datetime_field.models.NepaliDateField(),
        ),
    ]
