# Generated by Django 5.0.7 on 2024-12-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_alter_attendance_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="check_in_lat",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_in_lng",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out_lat",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out_lng",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="is_remote",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
