# Generated by Django 5.0.7 on 2024-12-11 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_attendance_check_in_lat_attendance_check_in_lng_and_more"),
        ("organization", "0047_organizationaddress_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteWorkPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_allowed", models.BooleanField(default=False, null=True)),
                (
                    "remote_lat",
                    models.CharField(db_default="", max_length=50, null=True),
                ),
                ("remote_lng", models.CharField(default="", max_length=50, null=True)),
                (
                    "employee",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.employee",
                    ),
                ),
            ],
        ),
    ]
