# Generated by Django 5.0.7 on 2024-12-11 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_remoteworkpermission"),
        ("organization", "0047_organizationaddress_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remoteworkpermission",
            name="employee",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="remote_work_permission",
                to="organization.employee",
            ),
        ),
    ]
