# Generated by Django 5.0.7 on 2024-12-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_alter_remoteworkpermission_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remoteworkpermission",
            name="remote_lat",
            field=models.CharField(default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="remoteworkpermission",
            name="remote_lng",
            field=models.CharField(default="", max_length=255, null=True),
        ),
    ]
