# Generated by Django 5.0.7 on 2024-12-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_alter_remoteworkpermission_remote_lat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remoteworkpermission",
            name="remote_lat",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="remoteworkpermission",
            name="remote_lng",
            field=models.FloatField(default=0),
        ),
    ]
