# Generated by Django 5.0.7 on 2026-07-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_remoteworkpermission_remote_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance/'),
        ),
    ]
