# Generated by Django 5.0.7 on 2026-07-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_attendance_check_in_photo_attendance_check_out_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
