# Generated by Django 5.0.6 on 2024-05-30 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0007_alter_employeedocument_employee_otherdocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySalaryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('BAI', 'Baishakh'), ('JES', 'Jestha'), ('ASH', 'Ashadh'), ('SHR', 'Shrawan'), ('BHA', 'Bhadra'), ('ASW', 'Ashwin'), ('KAR', 'Kartik'), ('MAN', 'Mangsir'), ('POU', 'Poush'), ('MAG', 'Magh'), ('FAL', 'Falgun'), ('CHA', 'Chaitra')], default='BAI', max_length=3)),
                ('issue_date', models.DateField()),
                ('basic_salary', models.FloatField(default=0)),
                ('tds', models.FloatField(default=0)),
                ('ssf', models.FloatField(default=0)),
                ('epf', models.FloatField(default=0)),
                ('citizen_investment_trust', models.FloatField(default=0)),
                ('insurance', models.FloatField(default=0)),
                ('description', models.FloatField(default=0)),
                ('total_receivable', models.FloatField(default=0)),
                ('employee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.employee')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
    ]
