# Generated by Django 5.0.6 on 2024-05-30 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_alter_employeedocument_employee_otherdocument_and_more'),
        ('salary_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysalarytransaction',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.employee'),
        ),
    ]
