# Generated by Django 5.0.6 on 2024-05-30 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal_year', '0001_initial'),
        ('salary_management', '0002_alter_monthlysalarytransaction_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalarytransaction',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiscal_year.fiscalyear'),
        ),
    ]
