# Generated by Django 5.0.6 on 2024-06-30 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_employee_basic_salary'),
        ('salary_management', '0003_monthlysalarytransaction_fiscal_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.FloatField(default=0, null=True)),
                ('ssf', models.FloatField(default=0, null=True, verbose_name='Social security fund (SSF)')),
                ('tds', models.FloatField(default=0, null=True, verbose_name='Tax deducted at source (TDS)')),
                ('epf', models.FloatField(default=0, null=True, verbose_name='Employee provident fund (EPF)')),
                ('citizen_investment_trust', models.FloatField(default=0, null=True)),
                ('insurance', models.FloatField(default=0, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255, null=True)),
                ('deduction_amount', models.CharField(max_length=255)),
                ('bonus', models.FloatField(default=0)),
                ('description', models.TextField(max_length=1500)),
                ('salary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salary_management.salary')),
            ],
        ),
        migrations.DeleteModel(
            name='MonthlySalaryTransaction',
        ),
    ]
