# Generated by Django 5.0.6 on 2024-06-30 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_employee_basic_salary'),
        ('salary_management', '0004_salary_salarytransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarytransaction',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organization'),
        ),
    ]
