# Generated by Django 5.0.6 on 2024-06-30 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_management', '0005_salarytransaction_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarytransaction',
            name='total_salary',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salarytransaction',
            name='salary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salary_management.salary', verbose_name='Employee'),
        ),
    ]
