# Generated by Django 5.0.6 on 2024-06-30 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary_management', '0006_salarytransaction_total_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarytransaction',
            name='description',
        ),
    ]
