# Generated by Django 5.0.6 on 2024-06-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_management', '0007_remove_salarytransaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarytransaction',
            name='deduction_amount',
            field=models.FloatField(max_length=255),
        ),
    ]
