# Generated by Django 5.0.6 on 2024-06-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_management', '0008_alter_salarytransaction_deduction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarytransaction',
            name='deduction_amount',
            field=models.FloatField(default=0),
        ),
    ]
