# Generated by Django 5.0.6 on 2024-06-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary_management', '0009_alter_salarytransaction_deduction_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarytransaction',
            old_name='bonus',
            new_name='bonus_amount',
        ),
    ]
