# Generated by Django 5.0.6 on 2024-07-02 07:58

import nepali_datetime_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary_management', '0010_rename_bonus_salarytransaction_bonus_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarytransaction',
            name='date',
            field=nepali_datetime_field.models.NepaliDateField(null=True),
        ),
    ]
