# Generated by Django 5.0.7 on 2024-07-25 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal_year', '0002_alter_fiscalyear_options_alter_fiscalyear_title'),
        ('salary_management', '0012_salary_fiscal_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='fiscal_year',
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='fiscal_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiscal_year.fiscalyear'),
        ),
    ]
