# Generated by Django 5.0.7 on 2024-07-25 08:29

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary_management', '0014_salarytransactionreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarytransaction',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
