# Generated by Django 5.0.7 on 2024-09-26 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organization",
            "0035_alter_employee_options_alter_employee_basic_salary_and_more",
        ),
        ("salary_management", "0015_salarytransaction_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salary",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="organization.employee"
            ),
        ),
    ]
