# Generated by Django 5.0.7 on 2024-11-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salary_management", "0017_alter_salary_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="salarytransaction",
            name="status",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
