# Generated by Django 5.0.7 on 2024-11-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("salary_management", "0018_salarytransaction_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salarytransaction",
            name="bonus_amount",
        ),
        migrations.RemoveField(
            model_name="salarytransaction",
            name="deduction_amount",
        ),
        migrations.RemoveField(
            model_name="salarytransaction",
            name="total_salary",
        ),
    ]
