# Generated by Django 5.0.7 on 2024-11-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salary_management", "0019_remove_salarytransaction_bonus_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salarytransaction",
            name="status",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
