# Generated by Django 5.0.7 on 2024-11-28 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0044_remove_department_department_lead"),
        ("salary_management", "0020_alter_salarytransaction_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salary",
            name="organization",
        ),
        migrations.AlterField(
            model_name="salary",
            name="employee",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary",
                to="organization.employee",
            ),
        ),
    ]
