# Generated by Django 5.0.7 on 2024-11-28 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0044_remove_department_department_lead"),
        ("salary_management", "0021_remove_salary_organization_alter_salary_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.organization",
            ),
        ),
    ]
