# Generated by Django 5.0.7 on 2024-12-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salary_management", "0022_salary_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="remote_salary",
            field=models.FloatField(default=0, null=True),
        ),
    ]
