# Generated by Django 5.0.7 on 2026-07-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_management', '0023_salary_remote_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarytransaction',
            name='manual_net_salary',
            field=models.FloatField(blank=True, null=True, verbose_name='Manually Entered Net Salary'),
        ),
    ]
