# Generated by Django 5.0.7 on 2026-07-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_management', '0024_salarytransaction_manual_net_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='stored_half_leaves',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='stored_holidays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='stored_net_salary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='stored_no_of_days_present',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='stored_paid_leaves',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='stored_unpaid_leaves',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
