# Generated by Django 5.0.7 on 2026-07-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_management', '0025_salary_deleted_at_salary_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='tax_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Tax Rate (%)'),
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='incentive',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Incentive / Bonus'),
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='total_expense',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Expense (Employer Cost)'),
        ),
    ]
