# Generated by Django 5.0.7 on 2026-07-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_management', '0026_add_tax_rate_incentive_total_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarytransaction',
            name='transaction_epf',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='transaction_ssf',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
