# Generated by Django 5.0.7 on 2026-07-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_management', '0027_salarytransaction_transaction_epf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarytransaction',
            name='transaction_epf',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='salarytransaction',
            name='transaction_ssf',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
