# Generated by Django 5.0.7 on 2026-07-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_management', '0028_alter_salarytransaction_transaction_epf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarytransaction',
            name='transaction_tds',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
