# Generated by Django 5.0.7 on 2026-07-27 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0052_employee_marital_status_organizationsettings'),
        ('salary_management', '0029_salarytransaction_transaction_tds'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarytransaction',
            name='bonus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bonus'),
        ),
        migrations.AlterField(
            model_name='salarytransaction',
            name='incentive',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Incentive'),
        ),
        migrations.CreateModel(
            name='BonusTaxBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.FloatField(default=0)),
                ('max_amount', models.FloatField(blank=True, help_text='Leave blank for no upper limit', null=True)),
                ('tax_percentage', models.FloatField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_tax_bands', to='organization.organization')),
            ],
            options={
                'ordering': ['order', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='IncentiveTaxBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.FloatField(default=0)),
                ('max_amount', models.FloatField(blank=True, help_text='Leave blank for no upper limit', null=True)),
                ('tax_percentage', models.FloatField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_tax_bands', to='organization.organization')),
            ],
            options={
                'ordering': ['order', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='SalaryTaxBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], default='single', max_length=10)),
                ('min_salary', models.FloatField(default=0)),
                ('max_salary', models.FloatField(blank=True, help_text='Leave blank for no upper limit', null=True)),
                ('tax_percentage', models.FloatField(default=0)),
                ('order', models.IntegerField(default=0, help_text='Lower number = first band')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_tax_bands', to='organization.organization')),
            ],
            options={
                'ordering': ['marital_status', 'order', 'min_salary'],
            },
        ),
    ]
