# Generated by Django 5.0.7 on 2026-07-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_performancecategory_performancereview_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereview',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
