# Generated by Django 5.0.7 on 2024-07-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal_year', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscalyear',
            options={'verbose_name': 'Fiscal year'},
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Fiscal year'),
        ),
    ]
