# Generated by Django 5.0.7 on 2026-07-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal_year', '0002_alter_fiscalyear_options_alter_fiscalyear_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscalyear',
            options={'ordering': ['-id'], 'verbose_name': 'Fiscal year'},
        ),
    ]
