# Generated by Django 5.0.7 on 2026-07-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0002_alter_notice_created_by_alter_notice_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
