// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7zdbC_kUoSzHJKFTYAqRvUUqRWz9szX8',
    appId: '1:890275161522:web:62e16b0a34c4a64362b0ab',
    messagingSenderId: '890275161522',
    projectId: 'fir-c8bc9',
    authDomain: 'fir-c8bc9.firebaseapp.com',
    storageBucket: 'fir-c8bc9.firebasestorage.app',
    measurementId: 'G-Q1VFFPKMRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnNfkFboSG9gQhaLk-i5nqaMhHgsHLX9o',
    appId: '1:890275161522:android:1050c1a7797e771862b0ab',
    messagingSenderId: '890275161522',
    projectId: 'fir-c8bc9',
    storageBucket: 'fir-c8bc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNUcWL8L9OrLglfU042gmpJ84sgAcok0c',
    appId: '1:890275161522:ios:5f61e6e13364ed1b62b0ab',
    messagingSenderId: '890275161522',
    projectId: 'fir-c8bc9',
    storageBucket: 'fir-c8bc9.firebasestorage.app',
    androidClientId: '890275161522-4v6h12pvp68u29d1rsflgrj5rl94i44d.apps.googleusercontent.com',
    iosClientId: '890275161522-dqr0o609gbm9pkd6bj9pbim2dael7r7p.apps.googleusercontent.com',
    iosBundleId: 'com.ems.emsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7zdbC_kUoSzHJKFTYAqRvUUqRWz9szX8',
    appId: '1:890275161522:web:3628041fb9e3735062b0ab',
    messagingSenderId: '890275161522',
    projectId: 'fir-c8bc9',
    authDomain: 'fir-c8bc9.firebaseapp.com',
    storageBucket: 'fir-c8bc9.firebasestorage.app',
    measurementId: 'G-9THJDG5GHG',
  );
}
