# Generated by Django 5.0.7 on 2024-11-29 08:43

import django.db.models.deletion
import django_ckeditor_5.fields
import nepali_datetime_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0044_remove_department_department_lead"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("anonymous", "Anonymous"),
                            ("identified", "Identified"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("reviewed", "Reviewed")],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", nepali_datetime_field.models.NepaliDateField()),
                ("updated_at", nepali_datetime_field.models.NepaliDateField()),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComplainReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                ("created_at", nepali_datetime_field.models.NepaliDateField()),
                ("updated_at", nepali_datetime_field.models.NepaliDateField()),
                (
                    "complain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="feedback.complain",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.employee",
                    ),
                ),
            ],
        ),
    ]
