# Generated by Django 5.0.7 on 2024-12-01 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_complain_organization_complainreply_organization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="complainreply",
            options={"verbose_name": "Reply", "verbose_name_plural": "Replies"},
        ),
    ]
