# Generated by Django 5.0.7 on 2024-12-01 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_alter_complainreply_options"),
        ("organization", "0044_remove_department_department_lead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complain",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("reviewed", "Reviewed")],
                default="pending",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="complain",
            name="visibility",
            field=models.CharField(
                choices=[("anonymous", "Anonymous"), ("identified", "Identified")],
                default="anonymous",
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ComplainCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complain_categories",
                        to="organization.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="complain",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="feedback.complaincategory",
            ),
        ),
    ]
