# Generated by Django 5.0.7 on 2024-12-01 07:12

import nepali_datetime_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_alter_complain_status_alter_complain_visibility_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="complaincategory",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="complaincategory",
            name="created_at",
            field=nepali_datetime_field.models.NepaliDateField(null=True),
        ),
        migrations.AddField(
            model_name="complaincategory",
            name="updated_at",
            field=nepali_datetime_field.models.NepaliDateField(null=True),
        ),
    ]
