# Generated by Django 5.0.7 on 2024-12-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0005_alter_complaincategory_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="complain",
            old_name="employee",
            new_name="owner",
        ),
    ]
